-- Migration 001: Create the core jobs table.
--
-- The jobs table is the authoritative record of every job in the system.
-- Redis is used as the fast-path queue; this table is the source of truth for
-- status, history, and auditability.

BEGIN;

-- Status enum ensures only valid transitions can be stored.
DO $$ BEGIN
    CREATE TYPE job_status AS ENUM (
        'pending',
        'running',
        'completed',
        'failed',
        'dead'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS jobs (
    -- id is a UUID v4 generated by the application layer (not the database)
    -- so the caller can reference the job immediately without a round-trip.
    id              UUID            PRIMARY KEY,

    -- type identifies the job handler to invoke (e.g. "send_email", "resize_image").
    type            TEXT            NOT NULL,

    -- payload is arbitrary JSON passed verbatim to the handler.
    payload         JSONB           NOT NULL DEFAULT '{}',

    -- priority ranges from 1 (lowest) to 10 (highest). Higher-priority jobs are
    -- dequeued before lower-priority ones within the same Redis sorted set.
    priority        SMALLINT        NOT NULL DEFAULT 5
                    CHECK (priority BETWEEN 1 AND 10),

    -- status tracks the lifecycle: pending → running → completed | failed → dead.
    status          job_status      NOT NULL DEFAULT 'pending',

    -- attempts counts how many times processing has been tried (including the
    -- current attempt if status = 'running').
    attempts        INTEGER         NOT NULL DEFAULT 0,

    -- max_attempts is the per-job retry ceiling. Once attempts >= max_attempts
    -- and the job fails, it is moved to the dead-letter queue.
    max_attempts    INTEGER         NOT NULL DEFAULT 5,

    -- queue_name allows logical partitioning of jobs into named queues
    -- (e.g. "default", "critical", "bulk").
    queue_name      TEXT            NOT NULL DEFAULT 'default',

    -- scheduled_at is the earliest time the job may be dequeued. Jobs with
    -- scheduled_at in the future are held in a Redis delay set.
    scheduled_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- created_at is set once at insert time.
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- started_at is set when a worker claims the job.
    started_at      TIMESTAMPTZ,

    -- completed_at is set when the job reaches a terminal state.
    completed_at    TIMESTAMPTZ,

    -- worker_id is the identifier of the worker that last processed this job.
    worker_id       TEXT,

    -- error_message stores the last error returned by the handler.
    error_message   TEXT
);

-- Indexes (IF NOT EXISTS requires PostgreSQL 9.5+).
CREATE INDEX IF NOT EXISTS idx_jobs_status_priority_scheduled
    ON jobs (status, priority DESC, scheduled_at ASC);

CREATE INDEX IF NOT EXISTS idx_jobs_queue_status
    ON jobs (queue_name, status);

CREATE INDEX IF NOT EXISTS idx_jobs_type_status
    ON jobs (type, status);

CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON jobs (created_at DESC);

COMMIT;
