// Package queue defines the core domain types for the job queue system.
// It declares Job, DLQEntry, WorkerInfo, and the Status constants that flow
// through every layer of the application.
package queue

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Status represents the lifecycle state of a job.
type Status string

const (
	// StatusPending means the job is waiting to be picked up by a worker.
	StatusPending Status = "pending"

	// StatusRunning means a worker has claimed the job and is executing it.
	StatusRunning Status = "running"

	// StatusCompleted means the job handler returned successfully.
	StatusCompleted Status = "completed"

	// StatusFailed means the job handler returned an error but the job may be retried.
	StatusFailed Status = "failed"

	// StatusDead means the job exhausted all retry attempts and was moved to the DLQ.
	StatusDead Status = "dead"
)

// PriorityMin is the lowest valid job priority.
const PriorityMin = 1

// PriorityMax is the highest valid job priority.
const PriorityMax = 10

// PriorityDefault is the priority assigned when none is specified by the caller.
const PriorityDefault = 5

// DefaultQueueName is the name of the default job queue.
const DefaultQueueName = "default"

// Job is the central domain object. It is persisted in PostgreSQL (authoritative
// state) and its ID is pushed into Redis sorted sets for fast dequeue ordering.
type Job struct {
	// ID is a UUID v4 generated by the application before the first insert.
	ID uuid.UUID `json:"id"`

	// Type identifies the handler responsible for processing this job
	// (e.g. "send_email", "resize_image").
	Type string `json:"type"`

	// Payload is arbitrary JSON data passed to the handler.
	Payload json.RawMessage `json:"payload"`

	// Priority is 1–10; higher values are dequeued first.
	Priority int `json:"priority"`

	// Status is the current lifecycle state.
	Status Status `json:"status"`

	// Attempts is the total number of processing attempts so far.
	Attempts int `json:"attempts"`

	// MaxAttempts is the ceiling on retries before the job is moved to the DLQ.
	MaxAttempts int `json:"max_attempts"`

	// QueueName is the logical partition this job belongs to.
	QueueName string `json:"queue_name"`

	// ScheduledAt is the earliest time the job may be dequeued.
	ScheduledAt time.Time `json:"scheduled_at"`

	// CreatedAt is set at insert time.
	CreatedAt time.Time `json:"created_at"`

	// StartedAt is set when a worker first claims the job.
	StartedAt *time.Time `json:"started_at,omitempty"`

	// CompletedAt is set when the job reaches a terminal state.
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// WorkerID is the identifier of the last worker that processed this job.
	WorkerID *string `json:"worker_id,omitempty"`

	// ErrorMessage is the last error string returned by the handler.
	ErrorMessage *string `json:"error_message,omitempty"`

	// Result is an optional JSON value stored by the handler on success.
	// Consumers can fetch it via GET /api/v1/jobs/:id/result.
	Result json.RawMessage `json:"result,omitempty"`

	// APIKeyID is the UUID of the API key that created this job.
	// Nil for jobs created without a DB-backed API key (open/static auth).
	APIKeyID *uuid.UUID `json:"api_key_id,omitempty"`

	// ExpiresAt is when the job should be auto-purged. Nil = never expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Tags is arbitrary key-value metadata attached at enqueue time.
	// Useful for filtering, tracing, or per-user/per-tenant attribution.
	Tags map[string]string `json:"tags,omitempty"`
}

// DLQEntry represents a job that has been permanently failed and moved to the
// dead-letter queue.
type DLQEntry struct {
	// ID is the original job id for full traceability.
	ID uuid.UUID `json:"id"`

	Type        string          `json:"type"`
	Payload     json.RawMessage `json:"payload"`
	Priority    int             `json:"priority"`
	QueueName   string          `json:"queue_name"`
	MaxAttempts int             `json:"max_attempts"`

	// DiedAt is when the entry was inserted into the DLQ.
	DiedAt time.Time `json:"died_at"`

	// OriginalCreatedAt is when the original job was first created.
	OriginalCreatedAt time.Time `json:"original_created_at"`

	// LastError is the error that caused the final failure.
	LastError *string `json:"last_error,omitempty"`

	// TotalAttempts is the total number of processing attempts made.
	TotalAttempts int `json:"total_attempts"`

	// Requeued is true if this entry has been manually re-enqueued.
	Requeued bool `json:"requeued"`

	// RequeuedAt is when the entry was re-enqueued.
	RequeuedAt *time.Time `json:"requeued_at,omitempty"`

	// NewJobID is the uuid of the new job created when this entry was requeued.
	NewJobID *uuid.UUID `json:"new_job_id,omitempty"`

	// APIKeyID is the UUID of the API key that originally created this job.
	APIKeyID *uuid.UUID `json:"api_key_id,omitempty"`

	// ExpiresAt is when the DLQ entry should be auto-purged. Nil = never expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// WorkerInfo is a snapshot of a worker's state at a point in time.
type WorkerInfo struct {
	// ID is the worker's unique identifier (typically hostname:pid:random).
	ID string `json:"id"`

	// Status is "active" while the worker is running, "stopped" after shutdown.
	Status string `json:"status"`

	// JobsProcessed is the cumulative number of successfully completed jobs.
	JobsProcessed int64 `json:"jobs_processed"`

	// JobsFailed is the cumulative number of permanently failed jobs.
	JobsFailed int64 `json:"jobs_failed"`

	// CurrentJobID is the job the worker is currently processing, or nil.
	CurrentJobID *uuid.UUID `json:"current_job_id,omitempty"`

	// StartedAt is when this worker process started.
	StartedAt time.Time `json:"started_at"`

	// LastSeen is the timestamp of the most recent heartbeat.
	LastSeen time.Time `json:"last_seen"`
}

// EnqueueRequest is the deserialized body of the POST /api/v1/jobs endpoint.
type EnqueueRequest struct {
	// Type is required; it must match a registered handler name.
	Type string `json:"type"`

	// Payload is optional arbitrary JSON forwarded to the handler.
	Payload json.RawMessage `json:"payload"`

	// Priority defaults to PriorityDefault when omitted or zero.
	Priority int `json:"priority"`

	// MaxAttempts defaults to the global config value when omitted or zero.
	MaxAttempts int `json:"max_attempts"`

	// QueueName defaults to DefaultQueueName when omitted.
	QueueName string `json:"queue_name"`

	// ScheduledAt defaults to now when omitted.
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`

	// TTLSeconds sets how long (in seconds) the job is kept after reaching a
	// terminal state. Zero means no expiry.
	TTLSeconds int `json:"ttl_seconds,omitempty"`

	// Tags is arbitrary key-value metadata forwarded to the stored job.
	Tags map[string]string `json:"tags,omitempty"`
}
